"""Problem 02."""

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms
# will be:

# - 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.


def fibonacci():
    """Create a generator for the Fibonacci sequence."""
    t1 = 0
    t2 = 1
    t3 = t1 + t2
    while True:
        t3 = t1 + t2
        t1 = t2
        t2 = t3
        yield t3


def accumulate(gen, pred, limit=10):
    """Accumulate items from a sequence."""
    acc = 0
    for x in gen:
        if x > limit:
            return acc
        if pred(x):
            acc += x
